### ISSUE TITLE
doc: Mac installation

### ISSUE THREAD

**Issue by neverchanje** [IppClub/Dora-SSR#9]
Hi there,

I'm interested in this project but I found no instruction for Mac installation in your doc https://dorothy-ssr.net/docs/tutorial/intro. My CPU is Apple M1 Pro.

**Comment by pigpigyyy** [comment]
Yes, the comands in CI are just for building test, and the arch is set to be x86_64 only for speeding up compilation.
Tried to add a Homebrew release, if you got Homebrew installed, you can just get a latest release with commands
```sh
brew tap pigpigyyy/dorothy-ssr
brew install --cask dorothy-ssr
```
Since the release is built by github action, the macOS system will warning you about "Untrusted developer". You just can ignore the message in the "Setting > Privacy and Security" panel.
